name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.release.outputs.RELEASE_BODY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Prepare the changelog
        id: prepare
        run: |
          touch CHANGES.md
          PREV_TAG=$(git describe --abbrev=0 --tags $(git rev-list --tags --max-count=1) 2> /dev/null)
          if [[ $PREV_TAG == v*.*.* ]]; then
            echo "::set-output name=latest::--latest"
          fi

      - name: Generate the changelog
        uses: orhun/git-cliff-action@v1.1.5
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --strip all ${{ steps.cliff_pre.outputs.latest }}
        env:
          OUTPUT: CHANGES.md

      - name: Update the release body
        id: release
        shell: bash
        run: |
          r=$(cat ${{ steps.git-cliff.outputs.changelog }})
          r="$(printf "$r" | tail -n +3)"
          r="${r//'%'/'%25'}"     # Multiline escape sequences for %
          r="${r//$'\n'/'%0A'}"   # Multiline escape sequences for '\n'
          r="${r//$'\r'/'%0D'}"   # Multiline escape sequences for '\r'
          echo "::set-output name=RELEASE_BODY::$r"

      # use release body in the same job
      - name: Publish on the GitHub releases
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: ${{ steps.release.outputs.RELEASE_BODY }}
