name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.release.outputs.RELEASE_BODY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Generate the changelog
        uses: orhun/git-cliff-action@v1.1.5
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --strip all --latest
        env:
          OUTPUT: CHANGES.md

      - name: Update the release body
        id: release
        shell: bash
        run: |
          r=$(cat ${{ steps.git-cliff.outputs.changelog }})
          r="$(printf "$r" | tail -n +3)"
          r="${r//'%'/'%25'}"     # Multiline escape sequences for %
          r="${r//$'\n'/'%0A'}"   # Multiline escape sequences for '\n'
          r="${r//$'\r'/'%0D'}"   # Multiline escape sequences for '\r'
          echo "::set-output name=RELEASE_BODY::$r"

  # use release body in another job
  upload:
    name: Upload the release
    needs: changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Setup PHP with tools
        uses: shivammathur/setup-php@2.15.0
        with:
          php-version: '7.4'
          tools: composer, phive

      - name: Generate the phar package
        run: |
          phive install humbug/box --force-accept-unsigned
          composer update --no-interaction --no-progress --no-dev --prefer-stable --optimize-autoloader
          composer info -D | sort
          tools/box compile

      - name: Publish on the GitHub releases
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/hiweb.phar
          tag: ${{ github.ref }}
          body: ${{ needs.changelog.outputs.release_body }}
